### ISSUE TITLE
Need to add simple animation for my card memory game

### ISSUE THREAD

**Issue by YesVladess** [YesVladess/Concentration-Game#1]
Add flip animations. Or maybe disappearing animation.
Or maybe add individual design for different 'theme' (group of emoji).

Any other additional features for making game more fun will do.

**Comment by BNTR** [comment]
Sorry, I have also made PR for this issue. I should have assign or leave a comment here that I started to do it. Anyway, you can look through it and maybe take approaches from the both of them)
